sudo: required
dist: trusty
language: cpp

compiler: clang
os: linux

install:
    - sudo apt-get -y update -qq && sudo apt-get -y install qt5-default libqt5svg5-dev graphviz

script:
    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
    - mkdir build
    - cd build
    - qmake ../dotter.pro CONFIG+=${BUILD_MODE}
    - make
    - ls -lRa .
    - file dotter/dotter
