os: linux
language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - graphviz
      - gcc-7
      - g++-7
      - qt510-meta-minimal
      - qt510svg
      - qt510tools

script:
    - export CC=gcc-7 ;
    - export CXX=g++-7 ;
    - source /opt/qt510/bin/qt510-env.sh ;
    - mkdir build
    - cd build
    - qmake ../dotter.pro
    - make
    - ls -lRa .
    - file dotter/dotter
